export const colorOptions = {
  'Auburn': 'a55728',
  'Black': '2c1b18',
  'Blonde': 'b58143',
  'Blonde Golden': 'd6b370',
  'Brown': '724133',
  'Brown Dark': '4a312c',
  'Pastel Pink': 'f59797',
  'Platinum': 'ecdcbf',
  'Red': 'c93305',
  'Silver Gray': 'e8e1e1',
  'Light': 'f8d25c',
  'Yellow': 'ffdbb4',
  'Blue': '65c9ff',
  'Green': '5199e4',
  'Pink': 'ff488e',
  'Gray': 'e6e6e6',
  'White': 'ffffff',
  'Transparent': 'transparent',
}


export const topOptions = {
  "Big Hair": "bigHair",
  "Bob": "bob",
  "Bun": "bun",
  "Curly": "curly",
  "Curvy": "curvy",
  "Dreads": "dreads",
  "Dreads 01": "dreads01",
  "Dreads 02": "dreads02",
  "Frida": "frida",
  "Frizzle": "frizzle",
  "Fro": "fro",
  "Fro Band": "froBand",
  "Hat": "hat",
  "Hijab": "hijab",
  "Long but not too Long": "longButNotTooLong",
  "Mia Wallace": "miaWallace",
  "Shaggy": "shaggy",
  "Shaggy Mullet": "shaggyMullet",
  "Shaved Sides": "shavedSides",
  "Short Curly": "shortCurly",
  "Short Flat": "shortFlat",
  "Short Round": "shortRound",
  "Short Waved": "shortWaved",
  "Sides": "sides",
  "Straight 01": "straight01",
  "Straight 02": "straight02",
  "Straight and Strand": "straightAndStrand",
  "The Caesar": "theCaesar",
  "The Caesar and Side Part": "theCaesarAndSidePart",
  "Turban": "turban",
  "Winter Hat 1": "winterHat1",
  "Winter Hat 02": "winterHat02",
  "Winter Hat 03": "winterHat03",
  "Winter Hat 04": "winterHat04",
}

export const mouthOptions = {
  "Concerned": "concerned",
  "Default": "default",
  "Disbelief": "disbelief",
  "Eating": "eating",
  "Grimace": "grimace",
  "Sad": "sad",
  "Scream Open": "screamOpen",
  "Serious": "serious",
  "Smile": "smile",
  "Tongue": "tongue",
  "Twinkle": "twinkle",
  "Vomit": "vomit",
}


export const facialHairOptions = {
  "Light Beard": "beardLight",
  "Majestic Beard": "beardMajestic",
  "Medium Beard": "beardMedium",
  "Fancy Moustache": "moustacheFancy",
  "Magnum Moustache": "moustacheMagnum",
};

export const accessoryOptions = {
  "Blank": "blank",
  "Eyepatch": "eyepatch",
  "Kurt Glasses": "kurt",
  "Prescription 01": "prescription01",
  "Prescription 02": "prescription02",
  "Round Glasses": "round",
  "Sunglasses": "sunglasses",
  "Wayfarers": "wayfarers",
};

export const clothingOptions = {
  "Blazer and Shirt": "blazerAndShirt",
  "Blazer and Sweater": "blazerAndSweater",
  "Collar and Sweater": "collarAndSweater",
  "Graphic Shirt": "graphicShirt",
  "Hoodie": "hoodie",
  "Overall": "overall",
  "Crew Neck Shirt": "shirtCrewNeck",
  "Scoop Neck Shirt": "shirtScoopNeck",
  "V-Neck Shirt": "shirtVNeck",
};

export const eyeTypeOptions = {
  "Closed": "closed",
  "Cry": "cry",
  "Default": "default",
  "Eye Roll": "eyeRoll",
  "Happy": "happy",
  "Hearts": "hearts",
  "Side": "side",
  "Squint": "squint",
  "Surprised": "surprised",
  "Wink": "wink",
  "Wacky Wink": "winkWacky",
  "xDizzy": "xDizzy",
};

export const eyebrowOptions = {
  "Angry": "angry",
  "Angry Natural": "angryNatural",
  "Default": "default",
  "Default Natural": "defaultNatural",
  "Flat Natural": "flatNatural",
  "Frown Natural": "frownNatural",
  "Raised Excited": "raisedExcited",
  "Raised Excited Natural": "raisedExcitedNatural",
  "Sad Concerned": "sadConcerned",
  "Sad Concerned Natural": "sadConcernedNatural",
  "Unibrow Natural": "unibrowNatural",
  "Up Down": "upDown",
  "Up Down Natural": "upDownNatural",
};
